<?php
/**
 * @file
 * Ting marcXchange module.
 *
 * Shows additional data on ting object page.
 */

define('TING_MARC_ADMIN', 'admin/config/ting/marc');

/**
 * Implements hook_menu().
 */
function ting_marc_menu() {
  $items = array();

  $items[TING_MARC_ADMIN] = array(
    'title' => 'Ting marcXchange',
    'description' => 'Configure additional marcXchange fields.',
    'page callback' => 'ting_marc_overview_page',
    'access arguments' => array('administer ting_marc settings'),
    'file' => 'ting_marc.admin.inc',
  );
  $items[TING_MARC_ADMIN . '/list'] = array(
    'title' => 'marcXchange fields',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'ting_marc.admin.inc',
  );

  $items[TING_MARC_ADMIN . '/settings'] = array(
    'title' => 'Module settings',
    'description' => 'Configure module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_marc_module_settings'),
    'access arguments' => array('administer ting_marc settings'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'ting_marc.admin.inc',
  );
  $items[TING_MARC_ADMIN . '/add'] = array(
    'title' => 'Add field',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_marc_edit_item', 'add'),
    'access arguments' => array('administer ting_marc settings'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'ting_marc.admin.inc',
  );
  $items[TING_MARC_ADMIN . '/%/edit'] = array(
    'title' => 'Edit setting',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_marc_edit_item', 'edit', 4),
    'access arguments' => array('administer ting_marc settings'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'ting_marc.admin.inc',
  );
  $items[TING_MARC_ADMIN . '/%/delete'] = array(
    'title' => 'Delete setting',
    'page callback' => 'ting_marc_delete_item',
    'page arguments' => array(4),
    'access arguments' => array('administer ting_marc settings'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'ting_marc.admin.inc',
  );

  $items['ting/marc/fields'] = array(
    'page callback' => 'ting_marc_field_js',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Get ting_marc settings from db for given type.
 *
 * These settings are set in admin interface.
 *
 * @param string $type
 *   Type name.
 *
 * @return array
 *   Settings.
 */
function _ting_marc_get_settings($type) {
  $res = db_select('ting_marc', 'tm')
    ->fields('tm')
    ->condition('tm.ting_type', $type)
    ->execute()->fetchAll();
  return $res;
}

/**
 * Implements hook_permission().
 */
function ting_marc_permission() {
  return array(
    'administer ting_marc settings' => array(
      'title' => t('Administer Ting marcXchange settings'),
    ),
  );
}

/**
 * Implements hook_secure_permissions().
 */
function ting_marc_secure_permissions($role) {
  $permissions = array(
    'administrators' => array(
      'administer ting_marc settings',
    ),
    'local administrator' => array(
      'administer ting_marc settings',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Create/update field using ting_marc settings.
 *
 * @param array $data
 *   A field definition array.
 */
function ting_marc_create_field($data) {
  $field_name = $data['field_name'];
  $weight = '';
  $field = field_info_field($field_name);

  if ($field) {
    $read_field = field_read_instance('ting_object', $field_name, 'ting_object');
    $weight = $read_field['display']['default']['weight'];
    $instance = field_info_instance('ting_object', $field_name, 'ting_object');
    field_purge_instance($instance);
    field_purge_field($field);
  }

  $weight = $weight ? $weight : '';

  $field = array(
    'field_name' => $field_name,
    'type' => 'ting_marc',
    'locked' => FALSE,
    'default_widget' => 'hidden',
    'no_ui' => TRUE,
    'entity_types' => array('ting_object'),
    'storage' => array(
      'type' => 'virtual_field',
    ),
  );
  field_create_field($field);

  $instance = array(
    'field_name' => $field_name,
    'label' => $data['marc_label'],
    'bundle' => 'ting_object',
    'entity_type' => 'ting_object',
    'settings' => array(
      'ting_type' => $data['ting_type'],
      'marc_field' => $data['marc_field'],
      'marc_subfield' => $data['marc_subfield'],
      'text_processing' => FALSE,
      'field_clickable' => $data['field_clickable'],
      'link_index' => $data['link_index'],
    ),
    'widget' => array(
      'type' => 'hidden',
    ),
    'formatter' => array(
      'type' => 'ting_marc_ajax_formatter',
    ),
    'display' => _ting_marc_field_display_settings($weight),
  );

  field_create_instance($instance);

  _ting_marc_add_field_to_groups($field_name);
}

/**
 * Get field view/group where ting_marc field must be added.
 *
 * @return array
 *   Associative array with key being field view and value group name.
 */
function _ting_marc_field_groups() {
  // Field view => field group mapping.
  return array(
    'default' => 'group_material_details',
  );
}

/**
 * Add ting_marc field to field groups.
 *
 * @param string $field_name
 *   Field name.
 */
function _ting_marc_add_field_to_groups($field_name) {
  $groups = _ting_marc_field_groups();
  foreach ($groups as $view => $group) {
    $field_group = field_group_load_field_group(
      $group,
      'ting_object',
      'ting_object',
      $view
    );
    if (is_object($field_group)) {
      if (!in_array($field_name, $field_group->children)) {
        $field_group->children[] = $field_name;
        field_group_group_save($field_group);
      }
    }
  }
  field_cache_clear();
}

/**
 * Display settings from ting_marc field.
 *
 * @param int $weight
 *   Weight of existing field, default null.
 *
 * @return array
 *   Associative array with keys being field view and values display settings.
 */
function _ting_marc_field_display_settings($weight = NULL) {
  $display_settings = array();
  $display_settings['default']['label'] = 'inline';

  if (!empty($weight)) {
    $display_settings['default']['weight'] = $weight;
  }

  return $display_settings;
}

/**
 * Purge ting_marc field.
 *
 * @param string $field_name
 *   Field name to be purged.
 */
function _ting_marc_purge_field($field_name) {
  // Remove field from groups.
  $groups = _ting_marc_field_groups();
  foreach ($groups as $view => $group) {
    $field_group = field_group_load_field_group(
      $group,
      'ting_object',
      'ting_object',
      $view
    );
    if (is_object($field_group)) {
      $index = array_search($field_name, $field_group->children);
      // Make sure no "deleted" fields remain.
      while ($index) {
        unset($field_group->children[$index]);
        $index = array_search($field_name, $field_group->children);
      }
      field_group_group_save($field_group);
    }
  }

  // Purge fields.
  $field = field_info_field($field_name);
  if ($field) {
    $instance = field_info_instance('ting_object', $field_name, 'ting_object');
    field_purge_instance($instance);
    field_purge_field($field);
  }

  field_cache_clear();
}

/**
 * Implements hook_field_info().
 *
 * Define 'ting_marc' field type.
 */
function ting_marc_field_info() {
  return array(
    'ting_marc' => array(
      'label' => t('Ting marcXchange'),
      'description' => t('Ting marcXchange field'),
      'default_widget' => 'hidden',
      'default_formatter' => 'ting_marc_ajax_formatter',
      'storage' => array(
        'type' => 'virtual_field',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 *
 * AJAX formatter for ting_marc fields.
 */
function ting_marc_field_formatter_info() {
  return array(
    'ting_marc_ajax_formatter' => array(
      'label' => t('Ajaxified'),
      'field types' => array('ting_marc'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function ting_marc_field_formatter_info_alter(&$info) {
  if (isset($info['hidden'])) {
    $info['hidden']['field types'][] = 'ting_marc';
  }
}

/**
 * Implements hook_widget_info_alter().
 */
function ting_marc_widget_info_alter(&$info) {
  if (isset($info['hidden'])) {
    $info['hidden']['field types'][] = 'ting_marc';
  }
}

/**
 * Implements hook_preprocess_field().
 */
function ting_marc_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_type'] == 'ting_marc') {
    $element = $variables['element'];

    $variables['label_hidden'] = ($element['#label_display'] == 'hidden');
    $variables['label'] = $variables['label_hidden'] ? NULL : check_plain($element['#title']);

    $variables['items'] = array();
    foreach ($element['#items'] as $delta => $item) {
      $variables['items'][$delta] = $element[$delta];
    }

    $variables['attributes_array'] = array(
      'data-ting-marc' => $variables['items'][0]['#markup'],
      'data-ting-clickable' => $variables['items'][0]['clickable'],
      'data-ting-link_index' => $variables['items'][0]['link_index'],
    );

    $variables['field_name_css'] = strtr($element['#field_name'], '_', '-');
    $variables['field_type_css'] = strtr($element['#field_type'], '_', '-');
    $variables['classes_array'] = array(
      'field',
      'field-name-' . $variables['field_name_css'],
      'field-type-' . $variables['field_type_css'],
      'field-label-' . $element['#label_display'],
      'ting-marc-unprocessed',
    );

    if ($element['#label_display'] == 'inline') {
      $variables['classes_array'][] = 'clearfix';
    }
  }
}

/**
 * Implements hook_field_formatter_view().
 */
function ting_marc_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  if ($display['type'] == 'ting_marc_ajax_formatter') {
    // Check if the field applies to entity.
    $types = array($entity->getType(), 'all');
    if (!in_array($instance['settings']['ting_type'], $types)) {
      return;
    }
    $element = array();
    $settings = $instance['settings'];
    // Build fake value for template preprocessor.
    $value = $entity->getId() . '|' . $settings['marc_field'] . '|' . $settings['marc_subfield'];

    $element[0]['#markup'] = $value;
    $element[0]['clickable'] = $settings['field_clickable'];
    $element[0]['link_index'] = $settings['link_index'];

    $mod_path = drupal_get_path('module', 'ting_marc');
    $element['#attached']['js'] = array(
      $mod_path . '/ting_marc.js' => array(),
      array(
        'data' => array('clickable' => $settings['field_clickable'], 'link_index' => $settings['link_index']),
        'type' => 'setting',
      ),
    );
    $element['#attached']['css'][] = $mod_path . '/ting_marc.css';

    return $element;
  }
}

/**
 * Implements hook_field_load().
 */
function ting_marc_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {
  foreach ($entities as $id => $entity) {
    $items[$id][0]['safe_value'] = '-';
    $items[$id][0]['value'] = '-';
  }
}

/**
 * Get field value.
 *
 * @param string $id
 *   Ting object ID.
 * @param string $field
 *   MarcXchnage field number.
 * @param string $subfield
 *   MarcXchnage subfield name.
 *
 * @return null|string
 *   Field value.
 */
function ting_marc_get_data($id, $field, $subfield) {
  // Handle data loading by other modules first.
  // All results will be merged.
  $result = module_invoke_all('marcxchange_data', $id, $field, $subfield);
  if (!empty($result)) {
    return implode(' ', $result);
  }

  // Default data loading: use core ting module's built-in funcionality to fetch
  // marc objects from the data well.
  module_load_include('client.inc', 'ting');
  $object = ting_get_object_marcxchange($id);
  if (empty($object)) {
    return NULL;
  }
  $res = $object->getValue($field, $subfield);
  return $res;
}

/**
 * Implements hook_ting_request_factory().
 */
function ting_marc_ting_request_factory() {
  return array('marcxchange' => 'ting_search_url');
}

/**
 * AJAX handler for field.
 */
function ting_marc_field_js() {
  $result = array();
  if (!empty($_POST)) {
    $fields = $_POST;

    foreach ($fields as $key => $field_data) {
      list($id, $field, $subfield) = explode('|', $field_data['data']);
      $value = ting_marc_get_data($id, $field, $subfield);

      if (!empty($value)) {
        $values = array();
        array_walk_recursive($value, function($v) use (&$values) {
          $values[] = $v;
        });
        if ($field_data['clickable']) {
          $links = array();
          foreach ($values as $value) {
            $links[] = l($value, 'search/ting/' . $field_data['link_index'] . '="' . $value . '"');
          }
          $value = implode(', ', $links);
        }
        else {
          $value = implode(', ', $values);
        }
        $result[$key][$field_data['data']] = $value;
      }
    }
  }
  drupal_json_output($result);
}
